#### bilexicon_logs_summary: Summarise logs ####################################

#' Summarise participant information
#'
#' @param data Logs, as generated by \code{bilexicon_logs}
#' @return A data frame with the sample size of each group, and the lis tof IDs in each group.
#' @examples
#' d <- bilexicon_logs_summary()

bilexicon_logs_summary <- function(

) {

  if (is.null(data)) {
    dat <- bilexicon_update(runs = runs)
    logs <- bilexicon_logs(dat)
  } else {
    dat <- data
  }

  bins_interest <- c("12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30")

  # summarise logs by age and language profile
  logs_summary <- logs %>%
    filter(completed) %>%
    group_by(age_bin, lp) %>%
    summarise(n = n(), id_db = list(id_db), .groups = "drop") %>%
    ungroup() %>%
    full_join(expand(., age_bin, lp), by = c("age_bin", "lp")) %>%
    rowwise() %>%
    mutate(id_db = paste0(unlist(id_db), collapse = ", "),
           n = ifelse(is.na(n), 0, n)) %>%
    ungroup() %>%
    filter(age_bin %in% bins_interest,
           lp %in% c("Monolingual", "Bilingual")) %>%
    janitor::clean_names()

  return(logs_summary)

}
