#### bilexicon_logs: Generate logs #############################################

#' Generate participant information and progress for each response
#'
#' @param data Responses data, as generated by \code{bilexicon_update}
#' @param runs Questionnaire versions to generate logs for
#' @param bilingual_threshold Minimum degree of exposure to consider a participant as *monolingual*.

#' @return A dataset with participant-level information (one row per response)
#' @examples
#' l <- bilexicon_logs(runs = c("formr-short", "formr-2"))
#'

bilexicon_logs <- function(
  responses = NULL,
  participants = NULL,
  google_email = NULL,
  bilingual_threshold = 95
) {
  bins <- c("< 10", "10-12", "12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30", "30-32", "32-34", "34-36", "36-38", "38-40", "> 40")
  bins_interest <- c("12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30")
  breaks <- c(0, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 60)

  if (is.null(responses)) {
    responses <- bilexicon_update(google_email = google_email)
  }

  if (is.null(participants)){
    participants <- bilexicon_participants(google_email = google_email)
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(total_items = sum(n),
              .groups = "drop")

  # generate logs
  logs <- responses %>%
    mutate(lp = case_when((doe_spanish >= bilingual_threshold | doe_catalan >= bilingual_threshold)  ~ "Monolingual",
                          between(doe_catalan, 100-bilingual_threshold, bilingual_threshold) &
                            between(doe_spanish, 100-bilingual_threshold, bilingual_threshold) ~ "Bilingual",
                          TRUE ~ "Other")) %>%
    group_by(id_db, date_birth, time, age, age_bin, sex, postcode, edu_parent1, edu_parent2, lp, doe_spanish, doe_catalan, time_stamp, code, study, version) %>%
    summarise(complete_items = sum(!is.na(response)), .groups = "drop") %>%
    left_join(total_items, by = c("version")) %>%
    left_join(select(participants, -date_birth), by = c("id_db", "time", "code", "study")) %>%
    mutate_at(vars(time_stamp), lubridate::as_datetime) %>%
    rowwise() %>%
    mutate(progress = 100*complete_items/total_items) %>%
    ungroup() %>%
    mutate(completed = progress >= 95,
           date_sent = lubridate::as_date(date_sent),
           time_stamp = lubridate::as_date(time_stamp),
           days_from_sent = as.numeric((time_stamp-date_sent), units = "days"),
           age_today = as.numeric((lubridate::today()-lubridate::as_date(date_birth)))/30,
           months_from_last_response = as.numeric(lubridate::today()-time_stamp)/30) %>%
    select(id, id_db, time, first_contact, date_sent, days_from_sent, time_stamp, date_birth, age, age_bin, sex, postcode, edu_parent1, edu_parent2, lp, doe_spanish, doe_catalan, code, study, version, progress, completed, age_today, months_from_last_response) %>%
    arrange(desc(time_stamp))
  #mutate(completed = ifelse(study %!in% c("BiLexiconShort", "Lockdown"), TRUE, completed))


  return(logs)

}
