#### ml_app: MultiLex GUI ------------------------------------------------------

#' Point-and-click interface for MultiLex
#' @import shiny
#' @import shinydashboard
#' @importFrom dplyr filter
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom dplyr arrange
#' @export ml_app
#' @param google_email E-mail used in Google Drive account.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @return A GUI that opens in the default browser
#' @examples
#' ml_app(email = "user@mail.com")
#'


ml_app <- function(
  participants = NULL,
  google_email = NULL
) {

  options(shiny.launch.browser = .rs.invokeShinyWindowExternal)

  #### prepare data ----------------------------------------------------------
  if (is.null(participants)){
    if (is.null(google_email)){
      google_email <- readline(prompt = "Google email: ")
    }
    participants <- ml_participants(google_email = google_email)
  }

  {
    studies <- c("BiLexicon", "BiLexiconShort", "CognatePriming", "DevLex", "Lockdown", "PhoCross", "phoCross2")
    cdi <- c("BL-Lockdown", "BL-Long-2", "CBC", "DevLex", "BL-Long-1", "BL-Short")
    version <- c("A", "B", "C", "D")
  }


  #### ui --------------------------------------------------------------------
  ui <- dashboardPage(
    skin = "black",
    dashboardHeader(title = "Participants"),
    dashboardSidebar(
      width = 150,
      sidebarMenu(
        menuItem("New participant",
                 tabName = "new_participant",
                 icon = icon("baby")),
        menuItem("Vocabulary",
                 tabName = "vocabulary",
                 icon = icon("language")),
        menuItem("Participants",
                 icon = icon("database"),
                 href = "https://docs.google.com/spreadsheets/d/164DMKLRO0Xju0gdfkCS3evAq9ihTgEgFiuJopmqt7mo/edit#gid=562619943")
      )
    ),
    dashboardBody(
      tabItems(
        tabItem(
          tabName = "new_participant",
          fluidRow(
            column(
              width = 5,
              status = "warning",
              box(
                status = "warning",
                textInput(inputId = "id",
                          label = "ID",
                          value = NA_integer_,
                          placeholder = "bilexicon_0000"),
                textInput(inputId = "id_exp",
                          label = "ID (experiment)",
                          value = NA_integer_,
                          placeholder = "cognatepriming00"),
                textInput(inputId = "id_db",
                          label = "ID (database)",
                          value = NA_integer_,
                          placeholder = "00000"),
                textInput(inputId = "code",
                          label = "Code",
                          value = paste0("BL", max(as.numeric(gsub("BL", "", participants$code)))+1),
                          placeholder = paste0("BL", max(as.numeric(gsub("BL", "", participants$code)))+1)),
                numericInput(inputId = "time",
                             label = "Time",
                             min = 1,
                             value = 1,
                             step = 1),
                dateInput(inputId = "date_birth",
                          label = "Date of birth",
                          max = lubridate::today(),
                          value = lubridate::today(),
                          weekstart = 1,
                          autoclose = TRUE)
              ),
              box(
                selectInput(inputId = "study",
                            label = "Study",
                            choices = studies,
                            selectize = TRUE,
                            multiple = FALSE,
                            selected = "BiLexicon"),
                dateInput(inputId = "date_test",
                          label = "Date of testing",
                          value = lubridate::today(),
                          weekstart = 1,
                          autoclose = TRUE),
                selectInput(inputId = "cdi",
                            label = "CDI",
                            choices = cdi,
                            selectize = TRUE,
                            multiple = FALSE),
                selectInput(inputId = "version",
                            label = "Version",
                            choices = version,
                            selectize = TRUE,
                            multiple = FALSE)
              ),
              box(
                selectInput(inputId = "call",
                            label = "Call status?",
                            choices = c("Successful", "Pending", "Try again", "Stop"),
                            selectize = TRUE,
                            multiple = FALSE,
                            selected = "BiLexicon"),
                checkboxInput(inputId = "email_ready",
                              label = "Email ready?",
                              value = FALSE),
                checkboxInput(inputId = "email_sent",
                              label = "Email sent?",
                              value = FALSE),
                checkboxInput(inputId = "reminded",
                              label = "Reminded?",
                              value = FALSE),
                checkboxInput(inputId = "completed",
                              label = "Completed?",
                              value = FALSE),
                dateInput(inputId = "date_sent",
                          label = "Date email was sent",
                          value = lubridate::today(),
                          weekstart = 1,
                          autoclose = TRUE),
                textInput(inputId = "comments",
                          label = "Comments")

              ),
              shinyalert::useShinyalert()
            ),
            column(width = 7, DT::dataTableOutput(outputId = "participants"))
          ),
          br(),
          fluidRow(
            column(
              width = 2,
              actionButton("send", "Save",
                           width = "100%",
                           icon = icon("save"),
                           style = "color: #fff; background-color: #3cc977; border-color: #3cc977"),
              br(),
              actionButton("email", "Email",
                           width = "100%",
                           icon = icon("envelope"),
                           style = "color: #fff; background-color: #34a4eb; border-color: #34a4eb"),
              br(),
              actionButton("close", "Close",
                           width = "100%",
                           icon = icon("times-circle"),
                           style = "color: #fff; background-color: #c8102f; border-color: #c8102f")
            ),
            column(
              width = 10,
              box(title = "Subject and URL",
                  solidHeader = TRUE,
                  textOutput("email_subject"),
                  br(),
                  textOutput("email_link")),
              box(title = "Body",
                  solidHeader = TRUE,
                  collapsible = TRUE,
                  textOutput("email_body"))
            )
          )
        )
      ),
      tabItem(tabName = "vocabulary",
              h2("In progres..."))
    )
  )

  #### server ----------------------------------------------------------------
  server <- function(input, output) {

    output$participants <- DT::renderDataTable({
      participants %>%
        mutate(index = as.numeric(gsub("bilexicon_", "", id))) %>%
        arrange(desc(index)) %>%
        select(id, id_db, code, time, cdi, version, comments) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          colnames = c("ID", "ID (DB)", "Code", "Time", "CDI", "Version", "Comments"),
          filter = "top",
          options = list(pageLength = 5, autoWidth = FALSE)
        ) %>%
        DT::formatStyle(columns = "id", fontWeight = "bold") %>%
        DT::formatStyle(columns = "code", fontWeight = "bold")
    })

    observeEvent(input$send, {
      row_data <- data.frame(
        id = input$id,
        id_exp = input$id_exp,
        id_db = input$id_db,
        code = input$code,
        time = input$time,
        date_birth = input$date_birth,
        age_now = as.numeric(lubridate::today()-lubridate::as_date(input$date_birth))/30,
        study = input$study,
        cdi = input$cdi,
        version = input$version,
        date_test = lubridate::as_date(input$date_test),
        date_sent = lubridate::as_date(input$date_sent),
        call = input$call,
        email_ready = input$email_ready,
        email_sent = input$email_sent,
        reminded = input$reminded,
        completed = input$completed,
        link = ifelse(input$cdi %in% c("BL-Lockdown", "BL-Short"),
                      paste0("https://bllockdown.formr.org?bl_code=", input$code, "&version=", input$version),
                      ""),
        comments = input$comments,
        last_edited = lubridate::now())
      suppressMessages({
        googlesheets4::sheet_append(ss = "164DMKLRO0Xju0gdfkCS3evAq9ihTgEgFiuJopmqt7mo",
                                    sheet = "Participants",
                                    data = row_data)
      })
      shinyalert::shinyalert("Saved", "Participant added successfully", type = "success")
    })

    observeEvent(input$email, {
      output$email_subject <- renderText({
        "¡Colabora en nuestra investigación! - Babylab Universitat Pompeu Fabra"
      })
      output$email_body <- renderText({
        "Estimada familia,

        Os escribimos desde el BabyLab de la Universitat Pompeu Fabra para haceros llegar un cuestionario en el que os preguntaremos algunos datos sobre el entorno lingüístico de NAME y si conoce las palabras de una lista. Sigue el siguiente enlace para acceder al cuestionario:

        ENLACE

        El cuestionario dura aproximadamente 30 minutos. Podéis encontrar más información sobre los estudios que realizamos en la página del Centro para el Cerebro y la Cognición de la Universitat Pompeu Fabra.

        Sin la participación de las familias nuestra investigación no sería posible.

        ¡Gracias por vuestra colaboración!\n\nSaludos,

        Daniela y Gonzalo"
      })
      output$email_link <- renderText({
        paste0("https://bllockdown.formr.org/?bl_code=", input$code, "&version=", input$version)
      })
    })

    observeEvent(input$close, {
      stopApp()
    })
  }

  # launch shiny ---------------------------------------------------------------
  shinyApp(ui, server)

}
