#' Point-and-click interface for MultiLex
#' @import shiny
#' @import ggplot2
#' @import dplyr
#' @import Cairo
#' @importFrom scales label_percent
#' @importFrom lubridate today
#' @importFrom lubridate now
#' @importFrom scales percent
#' @importFrom scales label_percent
#' @importFrom googlesheets4 sheet_append
#' @importFrom googlesheets4 gs4_has_token
#' @importFrom shinyalert useShinyalert
#' @importFrom shinyalert shinyalert
#' @importFrom utils head
#' @importFrom tidyr pivot_wider
#' @importFrom stringr str_to_sentence
#' @importFrom stringr str_remove_all
#' @importFrom janitor clean_names
#' @importFrom scales label_percent
#' @importFrom scales percent
#' @importFrom htmltools withTags
#' @export ml_app
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @return A GUI that opens MultiLex in the default browser
#'

ml_app <- function(
  participants = NULL,
  responses = NULL
) {

  appDir <- system.file("shiny", "ml_app", package = "multilex")
  if (appDir == "") {
    stop("Could not the app. Try re-installing multilex.", call. = FALSE)
  }
  shinyOptions(participants = participants, responses = responses)
  shiny::runApp(appDir, display.mode = "normal", launch.browser = TRUE)
}
