#' Point-and-click interface for MultiLex
#' @import shiny
#' @import shinydashboard
#' @import ggplot2
#' @importFrom dplyr filter
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom dplyr arrange
#' @importFrom dplyr relocate
#' @importFrom dplyr vars
#' @importFrom dplyr mutate_if
#' @importFrom dplyr pull
#' @importFrom tidyr pivot_wider
#' @importFrom stringr str_to_sentence
#' @importFrom janitor clean_names
#' @importFrom scales label_percent
#' @importFrom scales percent
#' @importFrom htmltools withTags
#' @export ml_app
#' @param google_email E-mail used in Google Drive account.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @return A GUI that opens MultiLex in the default browser
#' @examples
#' ml_app(email = "user@mail.com")
#'


ml_app <- function(
  participants = NULL,
  responses = NULL,
  google_email = NULL
) {

  #### prepare data ----------------------------------------------------------
  if (is.null(responses)) {
    if (is.null(participants)) {
      participants <- ml_participants(google_email = google_email)
    }
    responses <- ml_responses(google_email = google_email,
                              participants = participants)
  }

  {
    new_codes <- participants %>%
      filter(call=="Successful") %>%
      pull(code)
    studies <- c("BiLexicon", "BiLexiconShort", "CognatePriming", "DevLex", "Lockdown", "PhoCross", "phoCross2")
    cdi <- c("BL-Lockdown", "BL-Long-2", "CBC", "DevLex", "BL-Long-1", "BL-Short")
    version <- c("A", "B", "C", "D")
    vocabulary <- ml_vocabulary(participants, responses)
    logs <- ml_logs(participants, responses)
    norms <- ml_norms(participants, responses) %>%
      mutate(age_num = as.numeric(factor(age_bin, ordered = TRUE)))
    norms_processed <- norms %>%
      mutate(age_bin = factor(age_bin, ordered = TRUE)) %>%
      mutate_if(is.double, function(x) round(x*100, 0)) %>%
      mutate(value = paste0(proportion, "% [", ci_lower, "-", ci_upper, "]", " n=", n)) %>%
      select(te, label, language, ipa, age_bin, type, lp, item_dominance, value) %>%
      mutate(label = paste0(label, " /", ipa, "/")) %>%
      pivot_wider(
        names_from = c(type, item_dominance, language),
        values_from = c(value, label)
      ) %>%
      arrange(te, age_bin, lp) %>%
      select(
        te, age_bin, lp,
        label_understands_L1_Catalan,
        value_understands_L1_Catalan, value_understands_L2_Catalan,
        value_produces_L1_Catalan, value_produces_L2_Catalan,
        label_understands_L1_Spanish,
        value_understands_L1_Spanish, value_understands_L2_Spanish,
        value_produces_L1_Spanish, value_produces_L2_Spanish
      )
  }

  #### ui ---------------------------------------------------------------
  ui <- shinyUI(
    dashboardPage(
      skin = "black",
      dashboardHeader(
        title = "MultiLex"
      ),
      dashboardSidebar(
        width = 150,
        sidebar_menu <- sidebarMenu(
          id = "tabs",
          menuItem(
            text = "Dashboard",
            tabName = "tab_dashboard",
            icon = icon("tachometer-alt")
          ),
          menuItem(
            text = "Logs",
            tabName = "tab_logs",
            icon = icon("calendar-alt")
          ),
          menuItem(
            text = "Vocabulary",
            tabName = "tab_vocabulary",
            icon = icon("language")
          ),
          menuItem(
            text = "Norms",
            tabName = "tab_norms",
            icon = icon("percent")
          ),
          menuItem(
            text = "Pool",
            tabName = "tab_pool",
            icon = icon("list")
          ),
          menuItem(
            text = "Participants",
            icon = icon("user-friends"),
            href = "https://docs.google.com/spreadsheets/d/164DMKLRO0Xju0gdfkCS3evAq9ihTgEgFiuJopmqt7mo/edit#gid=562619943"
          ),
          menuItem(
            text = "New participant",
            tabName = "tab_new_participant",
            icon = icon("baby")
          ),
          menuItem(
            text = "GitHub",
            icon = icon("github"),
            href = "https://github.com/gongcastro/multilex"
          )
        )
      ),
      dashboardBody(
        tabItems(
          tabItem(
            tabName = "tab_dashboard",
            fluidRow(
              box(
                selectInput(
                  inputId = "dashboard_version",
                  label = "Version",
                  choices = c(
                    "BL-Long-1", "BL-Long-2",
                    "BL-Short-A", "BL-Short-B", "BL-Short-C", "BL-Short-D",
                    "BL-Lockdown-A", "BL-Lockdown-B", "BL-Lockdown-C", "BL-Lockdown-D"
                  ),
                  selectize = TRUE,
                  multiple = TRUE,
                  selected = c(
                    "BL-Long-1", "BL-Long-2",
                    "BL-Short-A", "BL-Short-B", "BL-Short-C", "BL-Short-D",
                    "BL-Lockdown-A", "BL-Lockdown-B", "BL-Lockdown-C", "BL-Lockdown-D"
                  )
                )
              ),
              box(
                sliderInput(
                  inputId = "dashboard_age",
                  label = "Age",
                  min = 1,
                  max = round(max(responses$age, na.rm = TRUE)),
                  value = c(1, round(max(responses$age, na.rm = TRUE))),
                  step = 1
                ),
              )
            ),
            fluidRow(
              box(
                plotOutput(outputId = "responses_dates")
              ),
              box(
                plotOutput(outputId = "responses_dates_summary")
              ),
              box(
                plotOutput(outputId = "responses_ages")
              ),
              box(
                plotOutput(outputId = "responses_lps")
              )
            )
          ),
          tabItem(
            tabName = "tab_logs",
            fluidRow(
              box(
                title = "New responses",
                footer = "This participants have not been marked as 'Successful' in the Participants database.",
                status = "warning",
                solidHeader = TRUE,
                collapsible = TRUE,
                DT::dataTableOutput(outputId = "logs_successful")
              )
            ),
            fluidRow(
              DT::dataTableOutput(outputId = "logs_all")
            )
          ),
          tabItem(
            tabName = "tab_vocabulary",
            DT::dataTableOutput(outputId = "vocabulary")
          ),
          tabItem(
            tabName = "tab_norms",
            fluidRow(
              column(
                width = 2,
                selectInput(
                  inputId = "norms_item",
                  label = "Item",
                  choices = unique(norms$item),
                  selected = "cat_casa",
                  multiple = TRUE,
                  selectize = TRUE
                ),
                checkboxGroupInput(
                  inputId = "norms_lp",
                  label = "Language profile",
                  choices = c("Bilingual", "Monolingual", "Other"),
                  selected = c("Bilingual", "Monolingual")
                ),
                checkboxGroupInput(
                  inputId = "norms_item_dominance",
                  label = "Item dominance",
                  choices = c("L1", "L2"),
                  selected = c("L1")
                )
              ),
              column(
                width = 10,
                plotOutput(outputId = "norms_plot")
              )
            ),
            fluidRow(
              DT::dataTableOutput(outputId = "norms_table")
            )
          ),
          tabItem(
            tabName = "tab_pool",
            DT::dataTableOutput(outputId = "pool")
          ),
          tab_responses <- tabItem(
            tabName = "tab_responses",
            h2("In progress...")
          ),
          tabItem(
            tabName = "tab_new_participant",
            fluidRow(
              column(
                width = 5,
                status = "warning",
                box(
                  status = "warning",
                  textInput(
                    inputId = "id",
                    label = "ID",
                    value = NA_integer_,
                    placeholder = "bilexicon_0000"
                  ),
                  textInput(
                    inputId = "id_exp",
                    label = "ID (experiment)",
                    value = NA_integer_,
                    placeholder = "cognatepriming00"
                  ),
                  textInput(
                    inputId = "id_db",
                    label = "ID (database)",
                    value = NA_integer_,
                    placeholder = "00000"
                  ),
                  textInput(
                    inputId = "code",
                    label = "Code",
                    value = paste0("BL", max(as.numeric(gsub("BL", "", participants$code)))+1),
                    placeholder = paste0("BL", max(as.numeric(gsub("BL", "", participants$code)))+1)
                  ),
                  numericInput(
                    inputId = "time",
                    label = "Time",
                    min = 1,
                    value = 1,
                    step = 1
                  ),
                  dateInput(
                    inputId = "date_birth",
                    label = "Date of birth",
                    max = lubridate::today(),
                    value = lubridate::today(),
                    weekstart = 1,
                    autoclose = TRUE
                  )
                ),
                box(
                  selectInput(
                    inputId = "study",
                    label = "Study",
                    choices = studies,
                    selectize = TRUE,
                    multiple = FALSE,
                    selected = "BiLexicon"
                  ),
                  dateInput(
                    inputId = "date_test",
                    label = "Date of testing",
                    value = lubridate::today(),
                    weekstart = 1,
                    autoclose = TRUE
                  ),
                  selectInput(
                    inputId = "cdi",
                    label = "CDI",
                    choices = cdi,
                    selectize = TRUE,
                    multiple = FALSE
                  ),
                  selectInput(
                    inputId = "version",
                    label = "Version",
                    choices = version,
                    selectize = TRUE,
                    multiple = FALSE
                  )
                ),
                box(
                  selectInput(
                    inputId = "call",
                    label = "Call status?",
                    choices = c("Successful", "Pending", "Try again", "Stop"),
                    selectize = TRUE,
                    multiple = FALSE,
                    selected = "BiLexicon"
                  ),
                  checkboxInput(
                    inputId = "email_ready",
                    label = "Email ready?",
                    value = FALSE
                  ),
                  checkboxInput(
                    inputId = "email_sent",
                    label = "Email sent?",
                    value = FALSE
                  ),
                  checkboxInput(
                    inputId = "reminded",
                    label = "Reminded?",
                    value = FALSE
                  ),
                  checkboxInput(
                    inputId = "completed",
                    label = "Completed?",
                    value = FALSE
                  ),
                  dateInput(
                    inputId = "date_sent",
                    label = "Date email was sent",
                    value = lubridate::today(),
                    weekstart = 1,
                    autoclose = TRUE
                  ),
                  textInput(
                    inputId = "comments",
                    label = "Comments"
                  )
                ),
                shinyalert::useShinyalert()
              ),
              column(
                width = 7,
                DT::dataTableOutput(outputId = "participants")
              )
            ),
            br(),
            fluidRow(
              column(
                width = 2,
                actionButton(
                  "send", "Save",
                  width = "100%",
                  icon = icon("save"),
                  style = "color: #fff; background-color: #3cc977; border-color: #3cc977"
                ),
                br(),
                actionButton(
                  "email", "Email",
                  width = "100%",
                  icon = icon("envelope"),
                  style = "color: #fff; background-color: #34a4eb; border-color: #34a4eb"
                ),
                br(),
                actionButton(
                  "close", "Close",
                  width = "100%",
                  icon = icon("times-circle"),
                  style = "color: #fff; background-color: #c8102f; border-color: #c8102f"
                )
              ),
              column(
                width = 10,
                box(
                  title = "Subject and URL",
                  solidHeader = TRUE,
                  textOutput("email_subject"),
                  br(),
                  textOutput("email_link")
                ),
                box(
                  title = "Body",
                  solidHeader = TRUE,
                  collapsible = TRUE,
                  textOutput("email_body")
                )
              )
            )
          )
        )
      )
    )
  )

  #### server ------------------------------------------------------------------
  server <- shinyServer(function(input, output) {

    # responses_ages --------------------------------------------------------
    output$responses_ages <- renderPlot({
      logs %>%
        filter(
          completed,
          version %in% input$dashboard_version,
          between(
            age,
            input$dashboard_age[1],
            input$dashboard_age[2]
          )
        ) %>%
        mutate(age = round(age)) %>%
        group_by(version, age) %>%
        summarise(n = n(), .groups = "drop") %>%
        ggplot(aes(x = age, y = n, fill = version)) +
        geom_col() +
        labs(x = "Age (months)", y = "N", fill = "Version") +
        theme_minimal() +
        theme(
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          axis.text = element_text(colour = "black"),
          axis.title = element_text(face = "bold"),
          legend.title = element_text(face = "bold")
        )
    })

    # responses_lps ------------------------------------------------------------
    output$responses_lps <- renderPlot({
      logs %>%
        filter(
          completed,
          version %in% input$dashboard_version,
          between(age,
                  input$dashboard_age[1],
                  input$dashboard_age[2]),
          lp != "Other"
        ) %>%
        mutate(
          age = round(age),
          doe2 = case_when(
            doe_spanish > doe_catalan ~ doe_catalan/100,
            doe_catalan > doe_spanish ~ doe_spanish/100,
            TRUE ~ 0.5
          ),
          doe2_cat = cut(doe2,
                         breaks = seq(0, 0.5, by = 0.1),
                         labels = c("0-10%", "10-20%", "20-30%", "30-40%", "40-50%"))
        ) %>%
        drop_na(doe2_cat) %>%
        group_by(age, doe2_cat) %>%
        summarise(n = n(), .groups = "drop") %>%
        ggplot(aes(x = age, y = doe2_cat, fill = n)) +
        geom_tile() +
        labs(x = "Age (months)", y = "Exposure to L2", fill = "N") +
        scale_x_continuous(breaks = seq(
          round(min(responses$age, na.rm = TRUE)),
          round(max(responses$age, na.rm = TRUE)),
          by = 2)
        ) +
        scale_fill_distiller(palette = "YlOrRd") +
        theme_minimal() +
        theme(panel.grid = element_blank(),
              axis.text = element_text(colour = "black"),
              axis.title = element_text(face = "bold"),
              legend.title = element_text(face = "bold"))
    })

    # responses_dates ----------------------------------------------------------
    output$responses_dates <- renderPlot({
      logs %>%
        filter(
          completed,
          version %in% input$dashboard_version,
          between(age,
                  input$dashboard_age[1],
                  input$dashboard_age[2])
        ) %>%
        arrange(version, time_stamp) %>%
        count(time_stamp, version) %>%
        group_by(version) %>%
        mutate(n = cumsum(n),
               n_label = max(n)) %>%
        ggplot(aes(x = time_stamp, y = n, colour = version)) +
        geom_line() +
        geom_label(aes(x = lubridate::today(),
                       y = n_label,
                       label = n_label),
                   show.legend = FALSE) +
        labs(x = "Time stamp", y = "N", colour = "Version") +
        theme_minimal() +
        theme(axis.text = element_text(colour = "black"),
              axis.title = element_text(face = "bold"),
              legend.title = element_text(face = "bold"))
    })

    # responses_dates_summary --------------------------------------------------
    output$responses_dates_summary <- renderPlot({
      logs %>%
        filter(completed,
               version %in% input$dashboard_version) %>%
        arrange(time_stamp) %>%
        count(time_stamp) %>%
        mutate(n = cumsum(n),
               n_label = max(n)) %>%
        ggplot(aes(x = time_stamp, y = n)) +
        geom_line() +
        geom_label(aes(x = lubridate::today(),
                       y = n_label,
                       label = n_label),
                   show.legend = FALSE) +
        labs(x = "Time stamp", y = "N", colour = "Version") +
        theme_minimal() +
        theme(axis.text = element_text(colour = "black"),
              axis.title = element_text(face = "bold"),
              legend.title = element_text(face = "bold"))
    })

    # logs ---------------------------------------------------------------------
    output$logs_all <- DT::renderDataTable({
      logs %>%
        select(id, id_exp, id_db, time, study, version, age, date_sent, time_stamp, progress) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          filter = "top",
          colnames = c("ID", "ID (Exp.)", "ID (DB)", "Time", "Study", "Version", "Age", "Date sent", "Time stamp", "Progress (%)"),
          options = list(
            pageLength = 8,
            autoWidth = TRUE
          )
        ) %>%
        DT::formatStyle(
          columns = "id",
          fontWeight = "bold"
        ) %>%
        DT::formatRound(
          columns = "age",
          digits = 0
        ) %>%
        DT::formatStyle(
          columns = "progress",
          backgroundColor = DT::styleEqual(c("100%"), c("#a5f0c7"))
        )
    })

    output$logs_successful <- DT::renderDataTable({
      logs %>%
        filter(progress %in% paste0(95:100, "%"),
               !(code %in% new_codes)) %>%
        select(id, id_exp, id_db, time, study, version, age, date_sent, time_stamp, progress) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          filter = "top",
          colnames = c("ID", "ID (Exp.)", "ID (DB)", "Time", "Study", "Version", "Age", "Date sent", "Time stamp", "Progress (%)"),
          options = list(
            pageLength = 8,
            autoWidth = TRUE
          )
        ) %>%
        DT::formatStyle(
          columns = "id",
          fontWeight = "bold"
        ) %>%
        DT::formatRound(
          columns = "age",
          digits = 0
        ) %>%
        DT::formatStyle(
          columns = "progress",
          backgroundColor = DT::styleEqual(c("100%"), c("#a5f0c7"))
        )
    })
    # norms_plot ---------------------------------------------------------------
    output$norms_plot <- renderPlot({
      norms %>%
        filter(
          te %in% unique(norms[norms$item %in% input$norms_item,]$te),
          lp %in% input$norms_lp,
          item_dominance %in% input$norms_item_dominance
        ) %>%
        mutate(type = str_to_sentence(type)) %>%
        ggplot(aes(
          x = as.factor(age_bin),
          y = proportion,
          ymin = ci_lower,
          ymax = ci_upper,
          colour = interaction(lp, item_dominance, sep = " - "),
          fill = interaction(lp, item_dominance, sep = " - "),
          group = interaction(lp, item_dominance, sep = " - "))
        ) +
        facet_grid(language~type) +
        geom_point(size = 3,
                   position = position_dodge(0.25),
                   show.legend = FALSE) +
        geom_hline(yintercept = 0.5, linetype = "dashed", colour = "black") +
        #geom_smooth(method = "loess", formula = "y ~ x", n = 3) +
        geom_errorbar(width = 0, size = 0.80, position = position_dodge(0.1)) +
        labs(x = "Age (months)",
             y = "Proportion",
             colour = "Group - Dominance",
             fill = "Group - Dominance",
             group = "Group - Dominance") +
        #guides(x = guide_axis(n.dodge = 2)) +
        scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
        scale_colour_brewer(palette = "Set1") +
        scale_fill_brewer(palette = "Set1") +
        theme_minimal() +
        theme(
          text = element_text(size = 12),
          strip.text = element_text(face = "bold", size = 13),
          axis.text = element_text(colour = "black", size = 12),
          axis.title = element_text(face = "bold"),
          legend.title = element_blank(),
          legend.position = "left"
        )

    })

    # norms_table --------------------------------------------------------------
    output$norms_table <- DT::renderDataTable({
      container <- withTags(table(
        class = 'display',
        thead(
          tr(
            th(colspan = 3, "Norms"),
            th(colspan = 5, "Catalan"),
            th(colspan = 5, "Spanish")
          ),
          tr(
            lapply(
              c("TE", "Age", "Group", rep(c("Item", "Comp. (L1)", "Comp. (L2)", "Prod. (L1)", "Prod. (L2)"), 2)),
              th
            )
          )
        )
      ))
      norms_processed %>%
        filter(
          te %in% unique(norms[norms$item %in% input$norms_item,]$te),
          lp %in% input$norms_lp
        ) %>%
        mutate(lp = case_when(
          lp=="Monolingual" ~ "ML",
          lp=="Bilingual" ~ "BL",
          lp=="Other" ~ "OT"
        )) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          filter = "none",
          container = container,
          options = list(
            pageLength = 15,
            autoWidth = TRUE
          )
        ) %>%
        DT::formatStyle(
          columns = c("age_bin", "lp"),
          fontWeight = "bold"
        ) %>%
        DT::formatStyle(
          columns = c(
            "label_understands_L1_Spanish",
            "value_understands_L1_Spanish", "value_understands_L2_Spanish",
            "value_produces_L1_Spanish", "value_produces_L2_Spanish"
          ),
          backgroundColor = "#e4e9f0"
        ) %>%
        DT::formatStyle(
          columns = c(
            "label_understands_L1_Catalan",
            "value_understands_L1_Catalan", "value_understands_L2_Catalan",
            "value_produces_L1_Catalan", "value_produces_L2_Catalan"
          ),
          backgroundColor = "white"
        ) %>%
        DT::formatStyle(
          columns = c(
            "te", "lp", "age_bin"
          ),
          backgroundColor = "orange",
          fontWeight = "bold"
        )
    })


    # vocabulary ---------------------------------------------------------------
    output$vocabulary <- DT::renderDataTable({
      vocabulary %>%
        mutate(vocab_prop = scales::label_percent(accuracy = 0.01)(vocab_prop),
               vocab_size = paste0(
                 vocab_count, "/",
                 vocab_n, " (",
                 vocab_prop, ")")
        ) %>%
        select(-c(vocab_count, vocab_n, vocab_prop)) %>%
        pivot_wider(
          id_cols = c(id, time),
          names_from = c(language, vocab_type),
          values_from = vocab_size
        ) %>%
        clean_names() %>%
        left_join(select(logs, id, age, time, study, version, time_stamp, progress),
                  by = c("id", "time")) %>%
        relocate(
          id,
          age,
          time,
          study,
          version,
          time_stamp,
          catalan_understands,
          spanish_understands,
          catalan_produces,
          spanish_produces,
          progress
        ) %>%
        arrange(desc(time_stamp)) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          filter = "top",
          colnames = c("ID", "Age", "Time", "Study", "Version", "Timestamp", "CAT (comp.)", "SPA (comp.)", "CAT (prod.)", "SPA (prod.)", "Progress"),
          options = list(
            pageLength = 15,
            autoWidth = TRUE
          )
        ) %>%
        DT::formatRound(
          columns = "age",
          digits = 0
        ) %>%
        DT::formatStyle(
          columns = "id",
          fontWeight = "bold"
        ) %>%
        DT::formatStyle(
          columns = c("catalan_understands", "catalan_produces"),
          backgroundColor = "#e4e9f0"
        ) %>%
        DT::formatStyle(
          columns = "progress",
          backgroundColor = DT::styleEqual(c("100%"), c("#a5f0c7"))
        )

    })

    # pool ---------------------------------------------------------------------
    output$pool <- DT::renderDataTable({
      container <- withTags(table(
        class = "display",
        thead(
          tr(
            th(colspan = 3, ""),
            th(colspan = 4, "Catalan"),
            th(colspan = 4, "Spanish")
          ),
          tr(
            lapply(
              c("TE", "Category", "Class", rep(c("Item", "Label", "IPA", "Frequency"), 2)),
              th
            )
          )
        )
      ))
      pool %>%
        select(te, label, ipa, item, language, category, class, frequency) %>%
        mutate(ipa = paste0("/", ipa, "/")) %>%
        pivot_wider(
          id_cols = c(te, category, class),
          names_from = "language",
          values_from = c(item, label, ipa, frequency),
          values_fn = first_non_na
        ) %>%
        arrange(te) %>%
        clean_names() %>%
        relocate(
          te, category, class,
          item_catalan, label_catalan, ipa_catalan, frequency_catalan,
          item_spanish, label_spanish, ipa_spanish, frequency_spanish
        ) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          filter = "top",
          container = container,
          options = list(
            pageLength = 15,
            autoWidth = TRUE
          )
        ) %>%
        DT::formatStyle(
          columns = "te",
          fontWeight = "bold"
        ) %>%
        DT::formatRound(
          columns = c("frequency_catalan", "frequency_spanish"),
          digits = 2
        ) %>%
        DT::formatStyle(
          columns = c("te", "category", "class"),
          backgroundColor = "orange"
        ) %>%
        DT::formatStyle(
          columns = "te",
          fontWeight = "bold"
        ) %>%
        DT::formatStyle(
          columns = c("item_catalan", "label_catalan", "ipa_catalan", "frequency_catalan"),
          backgroundColor = "white"
        ) %>%
        DT::formatStyle(
          columns = c("item_spanish", "label_spanish", "ipa_spanish", "frequency_spanish"),
          backgroundColor = "#e4e9f0"
        )
    })


    # participants -------------------------------------------------------------
    output$participants <- DT::renderDataTable({
      participants %>%
        mutate(index = as.numeric(gsub("bilexicon_", "", id))) %>%
        filter(id %in% input$id | id_db %in% input$id_db | code %in% input$code) %>%
        arrange(desc(index)) %>%
        select(id, id_db, code, time, cdi, version, completed, comments) %>%
        DT::datatable(
          rownames = FALSE,
          width = "1000px",
          height = "4000px",
          style = "bootstrap",
          colnames = c("ID", "ID (DB)", "Code", "Time", "CDI", "Version", "Completed", "Comments"),
          filter = "top",
          options = list(
            pageLength = 5,
            autoWidth = FALSE
          )
        ) %>%
        DT::formatStyle(
          columns = "id",
          fontWeight = "bold"
        ) %>%
        DT::formatStyle(
          columns = "code",
          fontWeight = "bold"
        )
    })

    # participants_send --------------------------------------------------------
    observeEvent(
      input$send, {
        row_data <- data.frame(
          id = input$id,
          id_exp = input$id_exp,
          id_db = input$id_db,
          code = input$code,
          time = input$time,
          date_birth = input$date_birth,
          age_now = as.numeric(lubridate::today()-lubridate::as_date(input$date_birth))/30,
          study = input$study,
          cdi = input$cdi,
          version = input$version,
          date_test = lubridate::as_date(input$date_test),
          date_sent = lubridate::as_date(input$date_sent),
          call = input$call,
          email_ready = input$email_ready,
          email_sent = input$email_sent,
          reminded = input$reminded,
          completed = input$completed,
          link = ifelse(
            input$cdi %in% c("BL-Lockdown", "BL-Short"),
            paste0(
              "https://bllockdown.formr.org?bl_code=",
              input$code,
              "&version=",
              input$version),
            ""),
          comments = input$comments,
          last_edited = lubridate::now())
        suppressMessages({
          googlesheets4::sheet_append(
            ss = "164DMKLRO0Xju0gdfkCS3evAq9ihTgEgFiuJopmqt7mo",
            sheet = "Participants",
            data = row_data
          )
        })
        shinyalert::shinyalert(
          "Saved",
          "Participant added successfully",
          type = "success"
        )
      })

    # participants_email -------------------------------------------------------
    observeEvent(
      input$email, {
        output$email_subject <- renderText({
          "¡Colabora en nuestra investigación! - Babylab Universitat Pompeu Fabra"
        })
        output$email_body <- renderText({
          "Estimada familia,

        Os escribimos desde el BabyLab de la Universitat Pompeu Fabra para haceros llegar un cuestionario en el que os preguntaremos algunos datos sobre el entorno lingüístico de NAME y si conoce las palabras de una lista. Sigue el siguiente enlace para acceder al cuestionario:

        ENLACE

        El cuestionario dura aproximadamente 30 minutos. Podéis encontrar más información sobre los estudios que realizamos en la página del Centro para el Cerebro y la Cognición de la Universitat Pompeu Fabra.

        Sin la participación de las familias nuestra investigación no sería posible.

        ¡Gracias por vuestra colaboración!\n\nSaludos,

        Daniela y Gonzalo"
        })
        output$email_link <- renderText({
          paste0(
            "https://bllockdown.formr.org/?bl_code=",
            input$code,
            "&version=",
            input$version
          )
        })
      })

    # participants_close -------------------------------------------------------
    observeEvent(
      input$close, {
        stopApp()
      })

  })
  # launch shiny ---------------------------------------------------------------
  shinyApp(
    ui = ui,
    server = server,
    options = options(shiny.launch.browser = .rs.invokeShinyWindowExternal)
  )

}
