#### ml_logs: Generate logs ####################################################

#' Generate participant information and progress for each response
#'
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param bilingual_threshold Minimum degree of exposure to consider a participant as *monolingual*.
#' @param google_email E-mail used in Google Drive account.
#' @return A dataset with participant-level information (one row per response)
#' @examples
#' l <- ml_logs(runs = c("formr-short", "formr-2"))
#'

ml_logs <- function(
  responses = NULL,
  participants = NULL,
  google_email = NULL,
  bilingual_threshold = 5,
  other_threshold = 10
) {
  bins <- c("< 10", "10-12", "12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30", "30-32", "32-34", "34-36", "36-38", "38-40", "> 40")
  bins_interest <- c("12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30")
  breaks <- c(0, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 60)

  if (is.null(responses)) {
    responses <- ml_responses(google_email = google_email)
  }

  if (is.null(participants)){
    participants <- ml_participants(google_email = google_email)
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(total_items = sum(n),
              .groups = "drop")

  # generate logs
  logs <- responses %>%
    mutate(age_bin = cut(age, breaks = breaks, labels = bins, ordered_result = TRUE) %>%
             factor(levels = bins, ordered = TRUE),
           lp = case_when(doe_catalan <= bilingual_threshold ~ "Monolingual",
                          doe_spanish <= bilingual_threshold ~ "Monolingual",
                          doe_others > other_threshold ~ "Other",
                          TRUE ~ "Bilingual"),
           dominance = case_when(doe_catalan > doe_spanish ~ "Catalan",
                                 doe_spanish > doe_catalan ~ "Spanish",
                                 doe_catalan==doe_spanish ~ sample(c("Catalan", "Spanish"), 1))) %>%
    group_by(id_db, date_birth, time, age, age_bin, sex, postcode, edu_parent1, edu_parent2, lp, doe_spanish, doe_catalan, time_stamp, code, study, version) %>%
    summarise(complete_items = sum(!is.na(response)), .groups = "drop") %>%
    left_join(total_items, by = c("version")) %>%
    left_join(select(participants, -date_birth), by = c("id_db", "time", "code", "study")) %>%
    mutate_at(vars(time_stamp), lubridate::as_datetime) %>%
    rowwise() %>%
    mutate(progress = 100*complete_items/total_items) %>%
    ungroup() %>%
    mutate(completed = progress >= 95,
           date_sent = lubridate::as_date(date_sent),
           time_stamp = lubridate::as_date(time_stamp),
           days_from_sent = as.numeric((time_stamp-date_sent), units = "days"),
           age_today = as.numeric((lubridate::today()-lubridate::as_date(date_birth)))/30,
           months_from_last_response = as.numeric(lubridate::today()-time_stamp)/30) %>%
    select(id, id_db, time, first_contact, date_sent, days_from_sent, time_stamp, date_birth, age, age_bin, sex, postcode, edu_parent1, edu_parent2, lp, doe_spanish, doe_catalan, code, study, version, progress, completed, age_today, months_from_last_response) %>%
    arrange(desc(time_stamp))
  #mutate(completed = ifelse(study %!in% c("BiLexiconShort", "Lockdown"), TRUE, completed))


  return(logs)

}
