#### ml_logs: Generate logs ####################################################

#' Generate participant information and progress for each response
#' @importFrom dplyr mutate
#' @importFrom dplyr case_when
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom dplyr left_join
#' @importFrom dplyr select
#' @importFrom dplyr mutate_at
#' @importFrom dplyr rowwise
#' @importFrom dplyr ungroup
#' @importFrom dplyr arrange
#' @importFrom scales label_percent
#' @importFrom lubridate as_date
#' @importFrom lubridate today
#' @export ml_logs
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param bilingual_threshold Minimum degree of exposure to consider a participant as *monolingual*.
#' @return A dataset with participant-level information (one row per response)
#' @examples
#' l <- ml_logs(runs = c("formr-short", "formr-2"))
#'

ml_logs <- function(
  participants = NULL,
  responses = NULL,
  google_email = NULL,
  bilingual_threshold = 5,
  other_threshold = 10
) {

  if (is.null(responses)) {
    if (is.null(participants)){
      participants <- ml_participants()
    }
    responses <- ml_responses(participants = participants)
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(total_items = sum(n),
              .groups = "drop")

  # generate logs
  logs <- responses %>%
    mutate(
      lp = case_when(
        doe_catalan <= bilingual_threshold ~ "Monolingual",
        doe_spanish <= bilingual_threshold ~ "Monolingual",
        doe_others > other_threshold ~ "Other",
        TRUE ~ "Bilingual"
      ),
      dominance = case_when(
        doe_catalan > doe_spanish ~ "Catalan",
        doe_spanish > doe_catalan ~ "Spanish",
        doe_catalan==doe_spanish ~ sample(c("Catalan", "Spanish"), 1))
    ) %>%
    group_by(id_db, date_birth, time, age, sex, postcode, edu_parent1, edu_parent2, dominance, lp, doe_spanish, doe_catalan, doe_others, time_stamp, code, study, version) %>%
    summarise(
      complete_items = sum(!is.na(response)),
      .groups = "drop"
    ) %>%
    left_join(
      total_items,
      by = c("version")) %>%
    left_join(
      select(
        participants,
        -c(date_birth, version)
      ),
      by = c("id_db", "time", "code", "study")
    ) %>%
    mutate_at(vars(time_stamp), lubridate::as_datetime) %>%
    rowwise() %>%
    mutate(
      progress = label_percent()(complete_items/total_items),
      completed = (complete_items/total_items)>= 0.95
    ) %>%
    ungroup() %>%
    mutate(
      date_sent = as_date(date_sent),
      time_stamp = as_date(time_stamp),
      days_from_sent = as.numeric((time_stamp-date_sent), units = "days"),
      age_today = as.numeric((today()-as_date(date_birth)))/30,
      months_from_last_response = as.numeric(today()-time_stamp)/30
    ) %>%
    select(id, id_exp, id_db, code, time, study, version, date_sent, time_stamp, days_from_sent, date_birth, age, age_today, months_from_last_response, sex, postcode, edu_parent1, edu_parent2, dominance, lp, doe_spanish, doe_catalan, doe_others, progress, completed) %>%
    arrange(desc(time_stamp))

  return(logs)

}
