#### ml_logs: Generate logs

#' Generate participant information and progress for each response
#' @import dplyr
#' @importFrom scales label_percent
#' @importFrom lubridate as_date
#' @importFrom lubridate today
#' @importFrom lubridate as_datetime
#' @importFrom rlang .data
#' @export ml_logs
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param bilingual_threshold Numeric scalar ranging from 0 to 1 indicating the minimum degree of exposure to Catalan or Spanish to consider a participant as *Monolingual*.
#' @param other_threshold Numeric scalar ranging from 0 to 1 indicating the minimum degree of exposure to languages other than Catalan and Spanish to consider a participant as *Other*.
#' @return A dataset with participant-level information (one row per response)
#'
ml_logs <- function(
  participants = NULL,
  responses = NULL,
  bilingual_threshold = 0.80,
  other_threshold = 0.10
) {

  ml_connect() # get credentials to Google and formr

  if (is.null(responses)) {
    if (is.null(participants)){
      participants <- ml_participants()
    }
    responses <- ml_responses(participants = participants)
  }

  suppressMessages({

    # get n items answered by participants (depends on the questionnaire version)
    total_items <- studies %>%
      distinct(.data$version, .data$language, .data$n) %>%
      group_by(.data$version) %>%
      summarise(
        total_items = sum(.data$n),
        .groups = "drop"
      )

    # generate logs
    logs <- responses %>%
      mutate(
        lp = case_when(
          .data$doe_catalan >= bilingual_threshold ~ "Monolingual",
          .data$doe_spanish >= bilingual_threshold ~ "Monolingual",
          .data$doe_others > other_threshold ~ "Other",
          TRUE ~ "Bilingual"
        ),
        dominance = case_when(
          .data$doe_catalan > .data$doe_spanish ~ "Catalan",
          .data$doe_spanish > .data$doe_catalan ~ "Spanish",
          .data$doe_catalan==.data$doe_spanish ~ sample(c("Catalan", "Spanish"), 1))
      ) %>%
      group_by_at(
        c(
          "id_db", "date_birth", "time", "age", "sex", "postcode",
          "edu_parent1", "edu_parent2", "dominance", "lp", "doe_spanish",
          "doe_catalan", "doe_others", "time_stamp", "code", "study", "version"
        )
      ) %>%
      summarise(
        complete_items = sum(!is.na(.data$response)), .groups = "drop"
      ) %>%
      left_join(total_items) %>%
      left_join(
        select(participants, -c(.data$date_birth, .data$version))
      ) %>%
      drop_na(.data$id) %>%
      mutate_at(vars(.data$time_stamp), as_datetime) %>%
      rowwise() %>%
      mutate(
        progress = label_percent()(.data$complete_items/.data$total_items),
        completed = (.data$complete_items/.data$total_items)>= 0.95
      ) %>%
      ungroup() %>%
      mutate(
        date_sent = as_date(.data$date_sent),
        time_stamp = as_date(.data$time_stamp),
        days_from_sent = as.numeric((.data$time_stamp-.data$date_sent), units = "days"),
        age_today = as.numeric((today()-as_date(.data$date_birth)))/30,
        months_from_last_response = as.numeric(today()-.data$time_stamp)/30
      ) %>%
      select(
        .data$id, .data$id_exp, .data$id_db, .data$code, .data$time, .data$study,
        .data$version, .data$date_sent, .data$time_stamp, .data$days_from_sent,
        .data$date_birth, .data$age, .data$age_today, .data$months_from_last_response,
        .data$sex, .data$postcode, .data$edu_parent1, .data$edu_parent2, .data$dominance,
        .data$lp, .data$doe_spanish, .data$doe_catalan, .data$doe_others,
        .data$progress, .data$completed
      ) %>%
      arrange(desc(.data$time_stamp))

  })

  return(logs)

}
