#### ml_responses: Update participant responses ################################

#' Retrieve and update local and/or remote data from formr
#'
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param formr_email E-mail used in formr account.
#' @param google_email E-mail used in Google Drive account.
#' @param runs formr runs to update
#' @return A dataframe containing participant's responses to each item, along with some session-specific metadata.
#' @examples
#' d <- ml_responses(formr_email = "user@mail.com", google_email = "user@mail.com", runs = c("formr-short", "formr-2"))

ml_responses <- function(
  participants = NULL,
  formr_email = "gonzalo.garciadecastro@upf.edu", # email (formr and Google Drive)
  google_email = NULL,
  runs = c("formr-2", "formr-lockdown") # c("inhibition", "devlex", "cbc", "formr-short", "formr1", "formr2", "formr-lockdown")
) {

  {
    formr_password <- readline(prompt = "Enter formr password: ")
  }

  #### set up #############################################

  # load packages
  formr::formr_connect(formr_email, password = formr_password) # get credentials
  message("Logged to platforms successfully")

  # define parameters
  items_to_keep <- c("code", "bl_code", "consent_mail", "demo_parent1", "demo_parent2", "demo_postcode", "sex", "language_doe_spanish", "language_doe_spanish_american", "language_doe_catalan_barcelona", "language_doe_catalan_majorca", "language_doe_catalan_other")
  bins <- c("< 10", "10-12", "12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30", "30-32", "32-34", "34-36", "36-38", "38-40", "> 40")
  bins_interest <- c("12-14", "14-16", "16-18", "18-20", "20-22", "22-24", "24-26", "26-28", "28-30")
  breaks <- c(0, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 60)

  #### import data ########################################
  if (is.null(participants)){
    participants <- ml_participants(google_email = google_email)
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(total_items = sum(n),
              .groups = "drop")

  formr2 <- import_formr2() # formr2
  formr_lockdown <- import_formr_lockdown() # formr-lockdown

  message("Data processed")

  #### merge data ###########################################################
  responses <- list(formr1, formr2, formr_short, formr_lockdown, cbc, inhibition, devlex) %>%
    bind_rows() %>%
    mutate(date_birth = lubridate::as_date(date_birth),
           time_stamp = lubridate::as_date(time_stamp),
           version = case_when(study %in% "DevLex" ~ "DevLex",
                               study %in% c("CBC", "Inhibition", "Signs", "Negation", "Inhibition") ~ "CBC",
                               TRUE ~ version),
           age_bin = cut(age, breaks = breaks, labels = bins, ordered_result = TRUE) %>%
             factor(levels = bins, ordered = TRUE),
           postcode = ifelse(nchar(postcode) < 5, paste0("0", postcode), postcode),
           postcode = ifelse(nchar(postcode) < 5, NA_character_, postcode),
           time = ifelse(is.na(time), 1, time)) %>%
    #distinct(id, id_db, time, language, item, .keep_all = TRUE) %>%
    drop_na(time_stamp) %>%
    group_by(id) %>%
    mutate(sex = sex[which(!is.na(sex))[1]]) %>%
    ungroup()

  message("Data merged")

  return(responses)

}
