#' Retrieve and update local and/or remote data from formr
#' @importFrom googlesheets4 gs4_has_token
#' @import dplyr
#' @importFrom tidyr drop_na
#' @importFrom lubridate as_date
#' @importFrom formr formr_connect
#' @export ml_responses
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param runs formr runs to update
#' @param longitudinal Should longitudinal data be included? If "all" (default), all responses (including repeated measures) are included. If "no", participants with more than one responses to the questionnaire (regardless of the version) are excluded. If "first", only the first response of each participant is included. If "last", only the last response of each participant is included. If "only", only responses with repeated measures are included.
#' @return A data frame containing participant's responses to each item, along with some session-specific metadata.
#' @examples
#' d <- ml_responses(runs = c("formr-short", "formr-2"), longitudinal = "last")

ml_responses <- function(
  participants = NULL,
  runs = c("BL-Long2", "BL-Lockdown"), # c("Inhibition", "DevLex", "CBC", "BL-Short", "BL-Long-1", "BL-Long-2", "BL-Lockdown")
  longitudinal = "all"
) {

  #### import data -------------------------------------------------------------
  # authenticate if n
  if (!gs4_has_token()){
    ml_connect()
  }

  if (is.null(participants)){
    participants <- ml_participants()
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(
      total_items = sum(n),
      .groups = "drop"
    )

  # retrieve data from formr
  formr2 <- import_formr2() # formr2
  formr_lockdown <- import_formr_lockdown() # formr-lockdown

  #### merge data ###########################################################
  responses <- list(formr1, formr2, formr_short, formr_lockdown, cbc, devlex) %>%
    bind_rows() %>%
    mutate(
      date_birth = as_date(date_birth),
      time_stamp = as_date(time_stamp),
      version = case_when(
        study %in% "DevLex" ~ "DevLex",
        study %in% c("CBC", "Signs", "Negation", "Inhibition") ~ "CBC",
        TRUE ~ version
      ),
      time = ifelse(is.na(time), 1, time),
      dominance = case_when(
        doe_catalan >= doe_spanish ~ "Catalan",
        doe_spanish > doe_catalan ~ "Spanish"
      )
    ) %>%
    fix_item() %>%
    fix_doe() %>%
    fix_postcode() %>%
    fix_sex() %>%
    drop_na(time_stamp) %>%
    get_longitudinal(longitudinal = longitudinal)

  return(responses)

}
