#### ml_responses: Update participant responses ################################

#' Retrieve and update local and/or remote data from formr
#' @import dplyr
#' @import tidyr
#' @export ml_responses
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param formr_email E-mail used in formr account.
#' @param google_email E-mail used in Google Drive account.
#' @param runs formr runs to update
#' @return A dataframe containing participant's responses to each item, along with some session-specific metadata.
#' @examples
#' d <- ml_responses(formr_email = "user@mail.com", google_email = "user@mail.com", runs = c("formr-short", "formr-2"))

ml_responses <- function(
  participants = NULL,
  formr_email = "gonzalo.garciadecastro@upf.edu", # email (formr and Google Drive)
  google_email = NULL,
  runs = c("BL-Long2", "BL-Lockdown") # c("Inhibition", "DevLex", "CBC", "BL-Short", "BL-Long-1", "BL-Long-2", "BL-Lockdown")
) {

  {formr_password <- readline(prompt = "Enter formr password: ")}

  #### import data -------------------------------------------------------------
  if (is.null(participants)){
    participants <- ml_participants(google_email = google_email)
  }

  total_items <- studies %>%
    distinct(version, language, n) %>%
    group_by(version) %>%
    summarise(total_items = sum(n),
              .groups = "drop")

  # retrieve data from formr
  formr::formr_connect(formr_email, password = formr_password) # get credentials
  formr2 <- import_formr2() # formr2
  formr_lockdown <- import_formr_lockdown() # formr-lockdown

  #### merge data ###########################################################
  responses <- list(formr1, formr2, formr_short, formr_lockdown, cbc, devlex) %>%
    bind_rows() %>%
    mutate(date_birth = lubridate::as_date(date_birth),
           time_stamp = lubridate::as_date(time_stamp),
           version = case_when(study %in% "DevLex" ~ "DevLex",
                               study %in% c("CBC", "Signs", "Negation", "Inhibition") ~ "CBC",
                               TRUE ~ version),
           postcode = ifelse(nchar(postcode) < 5, paste0("0", postcode), postcode),
           postcode = ifelse(nchar(postcode) < 5, NA_character_, postcode),
           time = ifelse(is.na(time), 1, time)) %>%
    drop_na(time_stamp) %>%
    fix_sex() %>%
    fix_doe()

  return(responses)

}
