#### ml_vocabulary: Compute vocabulary sizes ###################################

#' Generate participant information and progress for each response
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr filter
#' @importFrom dplyr group_by_at
#' @importFrom dplyr ungroup
#' @importFrom dplyr rename
#' @importFrom dplyr summarise
#' @importFrom dplyr rowwise
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr drop_na
#' @importFrom googlesheets4 gs4_has_token
#' @export ml_vocabulary
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param vocab_type Vocabulary type: "comprehensive" or "productive"
#' @param vocab_language Language to compute vocabulary sizes for: "catalan" and/or "spanish
#' @param keep_cols Columns to be kept in the output dataframe (apart from \code{id}, \code{time} and \code{language}).
#' @return A dataset with each participant's comprehensive and/or vocabulary size in each language
#' @examples
#' vocabulary <- ml_vocabulary()
#'

ml_vocabulary <- function(
  participants = NULL,
  responses = NULL,
  vocab_type = c("understands", "produces"),
  vocab_language = c("Catalan", "Spanish"),
  keep_cols = NULL
) {

  if (!gs4_has_token()){
    ml_connect()
  }

  if (is.null(responses)) {
    if (is.null(participants)){
      participants <- ml_participants()
    }
    responses <- ml_responses(participants = participants)
  }

  vocab <- responses %>%
    mutate(
      understands = response %in% c(2, 3),
      produces = response %in% 3
    ) %>%
    select(-response) %>%
    pivot_longer(c(understands, produces), names_to = "type", values_to = "response") %>%
    select(id, time, language, type, response, one_of(keep_cols)) %>%
    filter(type %in% vocab_type,
           language %in% vocab_language) %>%
    drop_na(response) %>%
    group_by_at(c("id", "time", "language", "type", keep_cols)) %>%
    summarise(
      vocab_count = sum(response, na.rm = TRUE),
      vocab_n = sum(!is.na(response)),
      .groups = "drop"
      ) %>%
    rowwise() %>%
    mutate(vocab_prop = vocab_count/vocab_n) %>%
    ungroup() %>%
    rename(vocab_type = type)

  return(vocab)

}
