#### ml_vocabulary: Compute vocabulary sizes ###################################

#' Generate participant information and progress for each response
#' @import dplyr
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr drop_na
#' @importFrom googlesheets4 gs4_has_token
#' @export ml_vocabulary
#' @param responses Responses data frame, as generated by \code{ml_responses}. If NULL (default), \code{ml_responses} is run.
#' @param participants Participants data frame, as generated by \code{ml_participants}. If NULL (default), \code{ml_participants} is run.
#' @param vocab_type Vocabulary type: "comprehensive" or "productive"
#' @return A dataset with each participant's comprehensive and/or vocabulary size in each language
#' @examples
#' vocabulary <- ml_vocabulary()
#'

ml_vocabulary <- function(
  participants = NULL,
  responses = NULL
) {

  if (!gs4_has_token()){
    ml_connect()
  }

  if (is.null(responses)) {
    if (is.null(participants)){
      participants <- ml_participants()
    }
    responses <- ml_responses(participants = participants)
  }

  vocab_base <- responses %>%
    mutate(
      understands = ifelse(is.na(response), NA, response %in% c(2, 3)),
      produces = ifelse(is.na(response), NA, response %in% c(3))
    ) %>%
    select(-response) %>%
    pivot_longer(c(understands, produces), names_to = "type", values_to = "response") %>%
    select(id, time, age, language, type, item, response)

  # total vocabulary
  vocab_total <- vocab_base %>%
    group_by(id, time, age, type) %>%
    summarise(
      vocab_count_total = sum(response, na.rm = TRUE),
      vocab_n_total = sum(!is.na(response)),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(vocab_prop_total = ifelse(vocab_n_total==0, 0, vocab_count_total/vocab_n_total)) %>%
    ungroup()

  # total vocabulary in Catalan
  vocab_total_catalan <- vocab_base %>%
    filter(language=="Catalan") %>%
    group_by(id, time, age, type) %>%
    summarise(
      vocab_count_catalan = sum(response, na.rm = TRUE),
      vocab_n_catalan = sum(!is.na(response)),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(vocab_prop_catalan = ifelse(vocab_n_catalan==0, 0, vocab_count_catalan/vocab_n_catalan)) %>%
    ungroup()

  # total vocabulary in Spanish
  vocab_total_spanish <- vocab_base %>%
    filter(language=="Spanish") %>%
    group_by(id, time, age, type) %>%
    summarise(
      vocab_count_spanish = sum(response, na.rm = TRUE),
      vocab_n_spanish = sum(!is.na(response)),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(vocab_prop_spanish = ifelse(vocab_n_spanish==0, 0, vocab_count_spanish/vocab_n_spanish)) %>%
    ungroup()

  # conceptual vocabulary
  vocab_conceptual <- vocab_base %>%
    left_join(select(pool, item, te), by = "item") %>%
    group_by(id, time, age, type, te) %>%
    summarise(
      vocab_count_conceptual = any(response),
      .groups = "drop"
    ) %>%
    group_by(id, time, age, type) %>%
    summarise(
      vocab_count_conceptual = sum(vocab_count_conceptual, na.rm = TRUE),
      vocab_n_conceptual = n(),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(vocab_prop_conceptual = ifelse(vocab_n_conceptual==0, 0, vocab_count_conceptual/vocab_n_conceptual)) %>%
    ungroup()

  # translation equivalents
  vocab_te <- vocab_base %>%
    left_join(select(pool, item, te), by = "item") %>%
    group_by(id, time, age, type, te) %>%
    summarise(
      vocab_count_te = (n()>1) & all(response),
      .groups = "drop"
    ) %>%
    group_by(id, time, age, type) %>%
    summarise(
      vocab_count_te = sum(vocab_count_te, na.rm = TRUE),
      vocab_n_te = n(),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(vocab_prop_te = ifelse(vocab_n_te==0, 0, vocab_count_te/vocab_n_te)) %>%
    ungroup()

  # merge all datasets
  vocab <- reduce(
    list(
      vocab_total,
      vocab_total_catalan,
      vocab_total_spanish,
      vocab_conceptual,
      vocab_te
    ),
    left_join,
    by = c("id", "time", "age", "type")
  )

  return(vocab)

}
